In [1]:
import warnings
from sklearn.exceptions import DataConversionWarning
warnings.filterwarnings(action='ignore', category=DataConversionWarning)
warnings.filterwarnings(action='ignore', category=RuntimeWarning)

In [3]:
from sklearn.datasets import *
import matplotlib.pyplot as plt
import numpy
import pandas as pd

In [17]:
import pandas as pd

df = pd.read_csv("/content/dataset.csv", header=None)
df.head()

,0,1,2,3,4,5,6,7,8,9,...,33,34,35,36,37,38,39,40,41,42
0,0.077549,0.730945,0.200171,0.730681,0.289466,0.599504,0.318780,0.466212,0.323937,0.377027,...,0.562516,0.052812,0.466041,0.072772,0.405951,0.075163,0.488114,0.074469,0.538946,A
1,0.108856,0.764239,0.212911,0.722015,0.284970,0.588672,0.308367,0.466420,0.317278,0.375470,...,0.569127,0.056657,0.475819,0.074178,0.396548,0.082307,0.483310,0.083130,0.542593,A
2,0.105847,0.773546,0.215779,0.723048,0.284620,0.589421,0.309289,0.469905,0.319025,0.380078,...,0.565446,0.055297,0.484447,0.072993,0.396703,0.085809,0.486615,0.089417,0.545101,A
3,0.105747,0.775406,0.215983,0.721042,0.285555,0.590549,0.311576,0.471254,0.320616,0.380149,...,0.566217,0.054352,0.485106,0.072243,0.395855,0.084705,0.486358,0.087859,0.545297,A
4,0.105010,0.776130,0.215287,0.722775,0.285534,0.592347,0.311326,0.471658,0.320882,0.380556,...,0.566444,0.054064,0.485248,0.071859,0.395500,0.084122,0.486592,0.086791,0.544902,A

In [26]:
len(df)

22697

In [27]:
df.iloc[:, -1].value_counts()

42
C    5974
D    5587
A    5578
B    5558
Name: count, dtype: int64

In [22]:
import pandas as pd

df_raw = pd.read_csv("/content/dataset.csv", header=None, engine="python")
print("raw rows:", len(df_raw))

raw rows: 22697

usable rows: 22697

In [24]:
df.shape

(22697, 43)

In [25]:
len(df)

22697

In [29]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

# Models
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC
from sklearn.neighbors import KNeighborsClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier

# โหลด dataset
df = pd.read_csv("/content/dataset.csv", header=None)

X = df.iloc[:, :-1]
y = df.iloc[:, -1]

# แบ่ง train / test
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

models = {
    "RandomForest": RandomForestClassifier(n_estimators=200),
    "SVM": SVC(),
    "KNN": KNeighborsClassifier(),
    "LogisticRegression": LogisticRegression(max_iter=1000),
    "DecisionTree": DecisionTreeClassifier()
}

results = {}

for name, model in models.items():
    model.fit(X_train, y_train)
    y_pred = model.predict(X_test)
    acc = accuracy_score(y_test, y_pred)
    results[name] = acc

# แสดงผล
for name, acc in results.items():
    print(f"{name}: {acc:.4f}")

RandomForest: 0.9993
SVM: 0.9993
KNN: 0.9996
LogisticRegression: 0.9985
DecisionTree: 0.9991